Quiet two errors from rust-analyzer
While developing locally, rust-analyzer consistently emits two errors at
startup:

 1. invalid config value: cargo/allFeatures: unexpected field

    This was a valid setting in the past; `true` meant `--all-features`.
    The `features` field does that now when set to `"all"`.

 2. FetchBuildDataError: error: failed to run custom build command for pgrx-pg-sys v0.18.1
    …
    Error: Multiple `pg$VERSION` features found. `--no-default-features` may be required.
      Found: pg13, pg14, pg17
      Location: pgrx-bindgen/src/lib.rs:64:28

    This was caused by differing default features across examples.